spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_trading?serverTimezone=UTC&characterEncoding=UTF-8
    username: root  # MySQL 계정
    password: 981020  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영에서는 validate 또는 none 사용 추천
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 Actuator 엔드포인트 활성화
  endpoint:
    health:
      show-details: always  # 상세한 시스템 상태 확인 가능
